# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img/', verbose_name='头像'),
        ),
    ]
