# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.IntegerField(default=0, verbose_name='reads')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.RemoveField(
            model_name='usercatagory',
            name='traffic',
        ),
        migrations.CreateModel(
            name='TrafficArticle',
            fields=[
                ('trafficmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_module.TrafficMixin')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarffic', to='blog_module.PublishArticle', verbose_name='article')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
            bases=('blog_module.trafficmixin',),
        ),
        migrations.CreateModel(
            name='TrafficCategory',
            fields=[
                ('trafficmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_module.TrafficMixin')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarffic', to='blog_module.UserCatagory', verbose_name='article')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
            bases=('blog_module.trafficmixin',),
        ),
    ]
