# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-22 16:05
from __future__ import unicode_literals

import blog_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_auto_20200322_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_module.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_module.models.user_directory_path),
        ),
    ]
